from pathlib import Path

path = Path('app.py')
s = path.read_text(encoding='utf-8')
old = '''        if position != 0:\n            age += 1\n            exit_price = None\n\n            if position == 1:\n                best = max(\n                    best,\n                    high[i],\n                )\n\n                if (\n                    best - entry\n                    >= risk_distance\n                    * params.get(\n                        "trail_trigger_r",\n                        1.0,\n                    )\n                ):\n                    stop = max(\n                        stop,\n                        best\n                        - atr[i]\n                        * params.get(\n                            "trail_atr",\n                            1.0,\n                        ),\n                    )\n\n                if low[i] <= stop:\n                    exit_price = stop\n                elif high[i] >= target:\n                    exit_price = target\n\n            else:\n                best = min(\n                    best,\n                    low[i],\n                )\n\n                if (\n                    entry - best\n                    >= risk_distance\n                    * params.get(\n                        "trail_trigger_r",\n                        1.0,\n                    )\n                ):\n                    stop = min(\n                        stop,\n                        best\n                        + atr[i]\n                        * params.get(\n                            "trail_atr",\n                            1.0,\n                        ),\n                    )\n\n                if high[i] >= stop:\n                    exit_price = stop\n                elif low[i] <= target:\n                    exit_price = target\n'''
new = '''        if position != 0:\n            age += 1\n            exit_price = None\n\n            # Conservative intrabar handling:\n            # evaluate the stop/target active at the candle open first.\n            # A trailing stop is updated only after the candle survives,\n            # so the current candle's high/low cannot retroactively move\n            # the stop and then trigger it in the same candle.\n            active_stop = stop\n\n            if position == 1:\n                if low[i] <= active_stop:\n                    exit_price = active_stop\n                elif high[i] >= target:\n                    exit_price = target\n\n                if exit_price is None:\n                    best = max(best, high[i])\n                    if (\n                        best - entry\n                        >= risk_distance\n                        * params.get(\n                            "trail_trigger_r",\n                            1.0,\n                        )\n                    ):\n                        stop = max(\n                            stop,\n                            best\n                            - atr[i]\n                            * params.get(\n                                "trail_atr",\n                                1.0,\n                            ),\n                        )\n\n            else:\n                if high[i] >= active_stop:\n                    exit_price = active_stop\n                elif low[i] <= target:\n                    exit_price = target\n\n                if exit_price is None:\n                    best = min(best, low[i])\n                    if (\n                        entry - best\n                        >= risk_distance\n                        * params.get(\n                            "trail_trigger_r",\n                            1.0,\n                        )\n                    ):\n                        stop = min(\n                            stop,\n                            best\n                            + atr[i]\n                            * params.get(\n                                "trail_atr",\n                                1.0,\n                            ),\n                        )\n'''
if old not in s:
    raise SystemExit('Expected backtest block not found; aborting without changes.')
s = s.replace(old, new, 1)
path.write_text(s, encoding='utf-8')
